version: '3.3'
services:
  angular-ui:
    build: .
    container_name: front-manager
    restart: always
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=manager.local.xyz
      - VIRTUAL_PORT=80
networks:
  default:
    external:
      name: nginx-proxy
