version: '3.3'
services:
  angular-ui:
    build: .
    container_name: front-manager
    restart: always
    expose:
      - 4200
    environment:
      - VIRTUAL_HOST=manager.vjdev.xyz
      - LETSENCRYPT_HOST=manager.vjdev.xyz
      - VIRTUAL_PORT=4200
networks:
    external:
      name: nginx-proxy      
